name: orchium

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  orchium:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /orchium') ||
      startsWith(github.event.comment.body, '/orchium')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - uses: ./.github/actions/setup-bun

      - name: Run orchium
        uses: MrHyplex9511/Orchium/github@dev # latest
        env:
          ORCHIUM_API_KEY: ${{ secrets.ORCHIUM_API_KEY }}
          ORCHIUM_PERMISSION: '{"bash": "deny"}'
        with:
          model: orchium/claude-opus-4-5
